package View;

import java.awt.event.ActionListener;

public class ViewMenuAdministrador extends javax.swing.JFrame {

    private ViewLogin viewLogin;

    public ViewMenuAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void exibirTela(){
        this.setVisible(true);
    }

    public void adicionarAcaoCadastrarConsulta(ActionListener acao){
        miCadastrarConsulta.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarExame(ActionListener acao){
        miCadastrarExame.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarEspecialidade(ActionListener acao){
        miEspecialidade.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarMedico(ActionListener acao){
        miMedico.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarLocal(ActionListener acao){
        miLocal.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarNomeExame(ActionListener acao){
        miCadastrarNomeeExame.addActionListener(acao);
    }

    public void adicionarAcaoSair(ActionListener acao){
        btSair.addActionListener(acao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadastrarConsulta = new javax.swing.JMenuItem();
        miCadastrarExame = new javax.swing.JMenuItem();
        miEspecialidade = new javax.swing.JMenuItem();
        miMedico = new javax.swing.JMenuItem();
        miLocal = new javax.swing.JMenuItem();
        miCadastrarNomeeExame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setSize(new java.awt.Dimension(300, 500));

        btSair.setText("Sair");

        jMenu1.setText("Cadastrar");

        miCadastrarConsulta.setText("Consulta");
        jMenu1.add(miCadastrarConsulta);

        miCadastrarExame.setText("Exame");
        jMenu1.add(miCadastrarExame);

        miEspecialidade.setText("Especialidade");
        jMenu1.add(miEspecialidade);

        miMedico.setText("Médico");
        jMenu1.add(miMedico);

        miLocal.setText("Local de Atendimento");
        jMenu1.add(miLocal);

        miCadastrarNomeeExame.setText("Tipo do Exame");
        jMenu1.add(miCadastrarNomeeExame);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btSair)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCadastrarConsulta;
    private javax.swing.JMenuItem miCadastrarExame;
    private javax.swing.JMenuItem miCadastrarNomeeExame;
    private javax.swing.JMenuItem miEspecialidade;
    private javax.swing.JMenuItem miLocal;
    private javax.swing.JMenuItem miMedico;
    // End of variables declaration//GEN-END:variables
}
